# Numpy Practical

In [34]:
import numpy as np

print(np.__version__)

1.19.2


## Section 3: Create Numpy Arrays

### Task 1

In [5]:
# 1a

np.arange(0,8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [6]:
# 1b

np.linspace(1.2,2.0,5)

array([1.2, 1.4, 1.6, 1.8, 2. ])

In [4]:
# 1c

np.array(['Mary', 'John', 'Peter', 'Christine'])

array(['Mary', 'John', 'Peter', 'Christine'], dtype='<U9')

In [7]:
# 1d

np.arange("2017-10-01", "2017-11-01", dtype="datetime64")

array(['2017-10-01', '2017-10-02', '2017-10-03', '2017-10-04',
       '2017-10-05', '2017-10-06', '2017-10-07', '2017-10-08',
       '2017-10-09', '2017-10-10', '2017-10-11', '2017-10-12',
       '2017-10-13', '2017-10-14', '2017-10-15', '2017-10-16',
       '2017-10-17', '2017-10-18', '2017-10-19', '2017-10-20',
       '2017-10-21', '2017-10-22', '2017-10-23', '2017-10-24',
       '2017-10-25', '2017-10-26', '2017-10-27', '2017-10-28',
       '2017-10-29', '2017-10-30', '2017-10-31'], dtype='datetime64[D]')

In [4]:
# 1e

np.random.random(10)

array([0.43878774, 0.53255357, 0.44747665, 0.67115098, 0.04640065,
       0.58789634, 0.28127718, 0.89088986, 0.12837574, 0.45430901])

In [12]:
# 1f

np.random.randint(100,201,(20))

array([154, 153, 133, 106, 186, 200, 183, 153, 154, 194, 188, 120, 173,
       114, 140, 171, 160, 130, 148, 122])

In [13]:
# 1g

np.linspace(5,10,50)

array([ 5.        ,  5.10204082,  5.20408163,  5.30612245,  5.40816327,
        5.51020408,  5.6122449 ,  5.71428571,  5.81632653,  5.91836735,
        6.02040816,  6.12244898,  6.2244898 ,  6.32653061,  6.42857143,
        6.53061224,  6.63265306,  6.73469388,  6.83673469,  6.93877551,
        7.04081633,  7.14285714,  7.24489796,  7.34693878,  7.44897959,
        7.55102041,  7.65306122,  7.75510204,  7.85714286,  7.95918367,
        8.06122449,  8.16326531,  8.26530612,  8.36734694,  8.46938776,
        8.57142857,  8.67346939,  8.7755102 ,  8.87755102,  8.97959184,
        9.08163265,  9.18367347,  9.28571429,  9.3877551 ,  9.48979592,
        9.59183673,  9.69387755,  9.79591837,  9.89795918, 10.        ])

### Task 2

In [18]:
# 2a

np.array([(1,2,3,4),(5,6,7,8)])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
# 2b

np.array([(1.5,2.5,3.5),(4.5,5.5,6.5),(7.5,8.5,9.5)])

array([[1.5, 2.5, 3.5],
       [4.5, 5.5, 6.5],
       [7.5, 8.5, 9.5]])

In [24]:
# 2c

np.array([(1.6,1.7,1.8),(2.5,5.0,7.5),(20,40,60)])

array([[ 1.6,  1.7,  1.8],
       [ 2.5,  5. ,  7.5],
       [20. , 40. , 60. ]])

In [25]:
# 2d

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
# 2e

np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
# 2f

np.full((4,3),10.5)

array([[10.5, 10.5, 10.5],
       [10.5, 10.5, 10.5],
       [10.5, 10.5, 10.5],
       [10.5, 10.5, 10.5]])

In [28]:
# 2g

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [34]:
# 2h

np.random.randint(1,7,(4,8))

array([[6, 6, 3, 3, 5, 5, 6, 4],
       [4, 3, 1, 6, 1, 2, 5, 5],
       [6, 6, 1, 6, 4, 6, 3, 2],
       [5, 1, 5, 5, 3, 3, 5, 3]])

## Section 4: Inspect Numpy Arrays

### Task 1

In [69]:
# 1a, b, c, d

a = np.array([1.55,1.73,1.9,1.72,1.66,1.8])
b = np.array([('red', 'green', 'yellow', 'blue'),(True,False, False, True), 
('2017-10-01', '2017-11-11', '2017-12-23', '2018-03-31')])
c = np.array([[(10,9,8,7),(6,5,4,3)], [(1,2,3,4),(5,6,7,8)]])
d = np.genfromtxt("data1.txt", delimiter=",", dtype="O") # Issues with handling multiple data types with np.loadtxt()

d

array([[b'red', b'green', b'yellow', b'blue'],
       [b'apple', b'orange', b'pear', b'durian'],
       [b'2017-08-12', b'2017-09-05', b'2017-10-18', b'2017-11-23'],
       [b'95', b'67', b'88', b'70']], dtype=object)

In [59]:
# np.shape

print(a.shape);print(b.shape);print(c.shape);print(d.shape)

(6,)
(3, 4)
(2, 2, 4)
(4, 4)


In [60]:
# len(ndarray)

print(len(a));print(len(b));print(len(c));print(len(d))

6
3
2
4


In [61]:
# np.ndim

print(a.ndim);print(b.ndim);print(c.ndim);print(d.ndim)

1
2
3
2


In [62]:
# np.size

print(a.size);print(b.size);print(c.size);print(d.size)

6
12
16
16


### Task 2

In [70]:
print(type(a), a.dtype);print(type(b), b.dtype);print(type(c), c.dtype);print(type(d), d.dtype)

<class 'numpy.ndarray'> float64
<class 'numpy.ndarray'> <U10
<class 'numpy.ndarray'> int32
<class 'numpy.ndarray'> object


## Section 5: Manipulating Array Shapes

### Task 1

In [79]:
a = np.array([ ['Mary', 'John','Bob'], 
               ['Zoe', 'Chris','Ann'],
               ['Leon', 'Kathy','Sam']])
a = a.flatten()
print(a, a.shape)

['Mary' 'John' 'Bob' 'Zoe' 'Chris' 'Ann' 'Leon' 'Kathy' 'Sam'] (9,)


### Task 2

In [82]:
# 2a

a = np.arange(15,30)
a = a.reshape(3,5)
print(a, a.shape)

[[15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]] (3, 5)


In [83]:
# 2b

b = np.array([ [1,2,3,4,5,6], [7,8,9,10,11,12]])
b = b.reshape(3,4)
print(b, b.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4)


### Task 3

In [87]:
a = np.array([ [1,2,3,4,5,6], [7,8,9,10,11,12]])
b = a.transpose()
c = np.transpose(a)
print(a, a.shape);print(b, b.shape);print(c, c.shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] (2, 6)
[[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]] (6, 2)
[[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]] (6, 2)


## Section 6: Manipulating Array Content

### Task 1

In [97]:
# 1a

a = np.array([[ 1,2,3],[ 4,5,6],[7,8,9]])
b = np.full((3,3),1.5)
c = np.arange(0,15).reshape(5,3)

np.concatenate((a,b,c), axis=0) # The axis along which the arrays will be joined. In this case, by Rows so Columns have the same number

array([[ 1. ,  2. ,  3. ],
       [ 4. ,  5. ,  6. ],
       [ 7. ,  8. ,  9. ],
       [ 1.5,  1.5,  1.5],
       [ 1.5,  1.5,  1.5],
       [ 1.5,  1.5,  1.5],
       [ 0. ,  1. ,  2. ],
       [ 3. ,  4. ,  5. ],
       [ 6. ,  7. ,  8. ],
       [ 9. , 10. , 11. ],
       [12. , 13. , 14. ]])

In [99]:
# 1b

a = np.array([[ 1,2,3,4],[ 4,5,6,7],[7,8,9,10],[11,12,13,14]])
b = np.random.randint(100,200,(4,6))
c = np.arange(0,40).reshape(4,10)

np.concatenate((a,b,c), axis=1) # Concatenate to Columns, so Rows must be the same.

array([[  1,   2,   3,   4, 165, 175, 168, 146, 127, 103,   0,   1,   2,
          3,   4,   5,   6,   7,   8,   9],
       [  4,   5,   6,   7, 116, 142, 156, 145, 106, 161,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19],
       [  7,   8,   9,  10, 157, 191, 180, 187, 136, 120,  20,  21,  22,
         23,  24,  25,  26,  27,  28,  29],
       [ 11,  12,  13,  14, 120, 142, 112, 126, 160, 145,  30,  31,  32,
         33,  34,  35,  36,  37,  38,  39]])

### Task 2

In [102]:
# 2a

x = np.arange(100)
x = np.split(x,20)

x

[array([0, 1, 2, 3, 4]),
 array([5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14]),
 array([15, 16, 17, 18, 19]),
 array([20, 21, 22, 23, 24]),
 array([25, 26, 27, 28, 29]),
 array([30, 31, 32, 33, 34]),
 array([35, 36, 37, 38, 39]),
 array([40, 41, 42, 43, 44]),
 array([45, 46, 47, 48, 49]),
 array([50, 51, 52, 53, 54]),
 array([55, 56, 57, 58, 59]),
 array([60, 61, 62, 63, 64]),
 array([65, 66, 67, 68, 69]),
 array([70, 71, 72, 73, 74]),
 array([75, 76, 77, 78, 79]),
 array([80, 81, 82, 83, 84]),
 array([85, 86, 87, 88, 89]),
 array([90, 91, 92, 93, 94]),
 array([95, 96, 97, 98, 99])]

In [104]:
# 2b

x = np.arange(100)
x = np.split(x,[10,25,45,75,95])

x

[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]),
 array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
        42, 43, 44]),
 array([45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
        62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74]),
 array([75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91,
        92, 93, 94]),
 array([95, 96, 97, 98, 99])]

## Section 7: Copying Arrays

### Task 1

In [35]:
# 1a

x = np.array([1,2,3])
y = x
z = np.copy(x)

print(x);print(y);print(z)

# No difference between y and z

[1 2 3]
[1 2 3]
[1 2 3]


In [38]:
# 1b

x = np.array([1, 2, 3])
y = x # The reason y takes on the old value of x is because it uses
# the new value of x since x variable has the same ID in memory
z = np.copy(x)
x[0] = 10 # Hmm, why does y take the new value of x but y is evaluated earlier on and shld thus follow x's old values?

In [37]:
print(x.sum());print(y.sum());print(z.sum()) # x is 15, y is 15 and z is 6.

15
15
6


In [42]:
print(id(x));print(id(y));print((id(z))) # Now you can see that x and y share the same ID

2363877638288
2363877638288
2363877638864


## Section 8: Sorting Arrays

### Task 1

In [195]:
# 1a

arr_1 = np.random.randint(100,200,10)

print("**Before sorting**")
print(arr_1)
print()

print("**After sorting**")
print(np.sort(arr_1))
print()

**Before sorting**
[151 159 137 196 157 133 107 182 121 139]

**After sorting**
[107 121 133 137 139 151 157 159 182 196]



In [200]:
# 1b

arr_2 = np.random.randint(1,20,(3,5))

print("**Before sorting**")
print(arr_2)
print()

print("**After sorting**")
print(np.sort(arr_2, axis=0))
print()

**Before sorting**
[[13  5 11 11 17]
 [17  1 13  5  6]
 [16 17  3  5  9]]

**After sorting**
[[13  1  3  5  6]
 [16  5 11  5  9]
 [17 17 13 11 17]]



In [203]:
# 1c

arr_3 = np.random.randint(100,200,(2,5))

print("**Before sorting - original array**")
print(arr_3)
print()

arr_3_sorted = np.sort(arr_3, axis=1)
print("**After calling sort method - original array**")
print(arr_3)
print()

print("**After calling sort method - copy of sorted array**")
print(arr_3_sorted)
print()

**Before sorting - original array**
[[192 162 186 156 146]
 [139 178 132 174 105]]

**After calling sort method - original array**
[[192 162 186 156 146]
 [139 178 132 174 105]]

**After calling sort method - copy of sorted array**
[[146 156 162 186 192]
 [105 132 139 174 178]]



## Section 9: Subsetting and Indexing

### Task 1

In [139]:
a = np.arange(1,100,1)
b = np.array([[1,2,3,4], [100,200,300,400],  [5,6,7,8],  [9,10,11,12] ])

print(a);print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]
[[  1   2   3   4]
 [100 200 300 400]
 [  5   6   7   8]
 [  9  10  11  12]]


In [141]:
# 1a
# a[3] is 4 with data type int32
# b[3] is [9 10 11 12] with data type int32

print(a[3], a[3].dtype);print(b[3], b[3].dtype)

4 int32
[ 9 10 11 12] int32


In [142]:
# 1b

b[1:3]

array([[100, 200, 300, 400],
       [  5,   6,   7,   8]])

In [150]:
# 1c

b[:,-1]

array([  4, 400,   8,  12])

In [177]:
# 1d

b[1,[0,-1]]

array([100, 400])

In [172]:
# 1e

b[2:,1:]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [180]:
# 1f

a[10:20:2]

array([11, 13, 15, 17, 19])

In [185]:
# 1g

a[::-1]

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

### Task 2

In [204]:
a = np.array((np.arange(0,10),
             np.arange(10,20),
             np.arange(20,30),
             np.arange(30,40)))

b = np.random.randint(100,200,(3,3))

print(a);print(b)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]
[[174 162 134]
 [199 134 196]
 [139 169 180]]


In [205]:
# 2a

# even = a % 2 == 0
# a[even]
a[a%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [206]:
# 2b

b[b>150]

array([174, 162, 199, 196, 169, 180])

### Task 3

In [214]:
b = np.arange(9.).reshape(3, 3)
b

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [217]:
b5 = np.where(b>5)
print(b5, len(b5))

(array([2, 2, 2], dtype=int64), array([0, 1, 2], dtype=int64)) 2


In [240]:
print("*** Values of where the elements are, and their rows/columns***")
for x in range(len(b5)+1):
    print("Value: {} in row {}, column {}".format(b[b5[0][x]][b5[1][x]], b5[0][x], b5[1][x]))

*** Values of where the elements are, and their rows/columns***
Value: 6.0 in row 2, column 0
Value: 7.0 in row 2, column 1
Value: 8.0 in row 2, column 2


In [241]:
# Workings to help visualize the index and len

print(b[2][0])
print(b[2][1])
print(b[2][2])

6.0
7.0
8.0


In [242]:
# Workings to help visualize the index and len

for x in range(len(b5)+1):
    print(x)

0
1
2


In [243]:
# Workings to help visualize the index and len

print(b5[0][0])
print(b5[0][1])
print(b5[0][2])

print(b5[1][0])
print(b5[1][1])
print(b5[1][2])

2
2
2
0
1
2


## Section 10: Array Math

### Task 1

In [7]:
# 1a

a = np.arange(100,200,1).reshape(20,5) 
b = np.arange(1,2000,20).reshape(10,10) 
c = np.array([[1,2,3], [4,5,6]])

a+b # Results in a ValueError since standard arithmetic operators such 
# as: +, -, , /, *, %, are applied on individual elements, so, 
# the arrays have to be of the same size

ValueError: operands could not be broadcast together with shapes (20,5) (10,10) 

In [9]:
# 1b

a2 = np.arange(100).reshape(20,5)
a + a2

array([[100, 102, 104, 106, 108],
       [110, 112, 114, 116, 118],
       [120, 122, 124, 126, 128],
       [130, 132, 134, 136, 138],
       [140, 142, 144, 146, 148],
       [150, 152, 154, 156, 158],
       [160, 162, 164, 166, 168],
       [170, 172, 174, 176, 178],
       [180, 182, 184, 186, 188],
       [190, 192, 194, 196, 198],
       [200, 202, 204, 206, 208],
       [210, 212, 214, 216, 218],
       [220, 222, 224, 226, 228],
       [230, 232, 234, 236, 238],
       [240, 242, 244, 246, 248],
       [250, 252, 254, 256, 258],
       [260, 262, 264, 266, 268],
       [270, 272, 274, 276, 278],
       [280, 282, 284, 286, 288],
       [290, 292, 294, 296, 298]])

In [10]:
# 1c

b

array([[   1,   21,   41,   61,   81,  101,  121,  141,  161,  181],
       [ 201,  221,  241,  261,  281,  301,  321,  341,  361,  381],
       [ 401,  421,  441,  461,  481,  501,  521,  541,  561,  581],
       [ 601,  621,  641,  661,  681,  701,  721,  741,  761,  781],
       [ 801,  821,  841,  861,  881,  901,  921,  941,  961,  981],
       [1001, 1021, 1041, 1061, 1081, 1101, 1121, 1141, 1161, 1181],
       [1201, 1221, 1241, 1261, 1281, 1301, 1321, 1341, 1361, 1381],
       [1401, 1421, 1441, 1461, 1481, 1501, 1521, 1541, 1561, 1581],
       [1601, 1621, 1641, 1661, 1681, 1701, 1721, 1741, 1761, 1781],
       [1801, 1821, 1841, 1861, 1881, 1901, 1921, 1941, 1961, 1981]])

In [17]:
b1 = b[0][0:6].reshape(2,3) # Since c has a shape of 2x3

b1 + c

array([[  2,  23,  44],
       [ 65,  86, 107]])

In [22]:
# 1d

mask_even = a%2==0
a2 = a[mask_even][0:6].reshape(2,3)

print(a2, a2.shape, c.shape)

[[100 102 104]
 [106 108 110]] (2, 3) (2, 3)


In [23]:
a2 * c

array([[100, 204, 312],
       [424, 540, 660]])

In [25]:
c2 = c * 10
c2

array([[10, 20, 30],
       [40, 50, 60]])

In [26]:
a2 / c2

array([[10.        ,  5.1       ,  3.46666667],
       [ 2.65      ,  2.16      ,  1.83333333]])

## Section 11: Statistical Methods

### Task 1

In [13]:
# 1a

a = np.array((np.arange(0,10),
            np.arange(10,20),
            np.arange(20,30),
            np.arange(30,40)))

print("Contents of array a\n", a)

Contents of array a
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]


In [14]:
print("*** Sum of all numbers in a***\n", a.sum())
# np.sum(a)

*** Sum of all numbers in a***
 780


In [15]:
# 1b

print("*** Means of all numbers in a***\n", a.mean())
# np.mean(a)

*** Means of all numbers in a***
 19.5


In [22]:
# 1c

print("*** Sum of all numbers in each row ***")
for x in range(4):
    print("Row {} sum = {}".format(x+1, a.sum(axis=1)[x]))

*** Sum of all numbers in each row ***
Row 1 sum = 45
Row 2 sum = 145
Row 3 sum = 245
Row 4 sum = 345


### Task 2

In [29]:
# Task 2a

a = np.arange(10,50,0.5)
b = np.arange(10,20,0.1)

print("Contents of array a\n",a,"\n\nContents of array b\n",b)

Contents of array a
 [10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5 15.  15.5 16.  16.5
 17.  17.5 18.  18.5 19.  19.5 20.  20.5 21.  21.5 22.  22.5 23.  23.5
 24.  24.5 25.  25.5 26.  26.5 27.  27.5 28.  28.5 29.  29.5 30.  30.5
 31.  31.5 32.  32.5 33.  33.5 34.  34.5 35.  35.5 36.  36.5 37.  37.5
 38.  38.5 39.  39.5 40.  40.5 41.  41.5 42.  42.5 43.  43.5 44.  44.5
 45.  45.5 46.  46.5 47.  47.5 48.  48.5 49.  49.5] 

Contents of array b
 [10.  10.1 10.2 10.3 10.4 10.5 10.6 10.7 10.8 10.9 11.  11.1 11.2 11.3
 11.4 11.5 11.6 11.7 11.8 11.9 12.  12.1 12.2 12.3 12.4 12.5 12.6 12.7
 12.8 12.9 13.  13.1 13.2 13.3 13.4 13.5 13.6 13.7 13.8 13.9 14.  14.1
 14.2 14.3 14.4 14.5 14.6 14.7 14.8 14.9 15.  15.1 15.2 15.3 15.4 15.5
 15.6 15.7 15.8 15.9 16.  16.1 16.2 16.3 16.4 16.5 16.6 16.7 16.8 16.9
 17.  17.1 17.2 17.3 17.4 17.5 17.6 17.7 17.8 17.9 18.  18.1 18.2 18.3
 18.4 18.5 18.6 18.7 18.8 18.9 19.  19.1 19.2 19.3 19.4 19.5 19.6 19.7
 19.8 19.9]


In [30]:
print("*** Standard deviation ***\nSD of a: ",np.std(a),"\nSD of b: ",np.std(b))

*** Standard deviation ***
SD of a:  11.546103238755489 
SD of b:  2.8866070047722014


In [31]:
# 2b

print("*** Variance ***\nVAR of a: ",np.var(a),"\nVAR of b: ",np.var(b))

*** Variance ***
VAR of a:  133.3125 
VAR of b:  8.332499999999941


### Task 3

In [76]:
a = np.random.randint(1,1000,(3,4))

print("***Contents of array a\n",a)

***Contents of array a
 [[105 483 857 659]
 [503 274 310 912]
 [347 655 459 209]]


In [106]:
# Max value of each row in array a

a.max(axis=1)

array([857, 912, 655])

In [104]:
# Max value of entire array and its row and column

print("Max a = ", a.max())
b = np.unravel_index(np.argmax(a), a.shape) # See: https://numpy.org/doc/stable/reference/generated/numpy.argmax.html?highlight=argmax#numpy.argmax
print("Row and Column of {} is ([{}], [{}])".format(a.max(), b[0], b[1]))

Max a =  912
Row and Column of 912 is ([1], [3])


In [107]:
# Min value of each column in array a

a.min(axis=0)

array([105, 274, 310, 209])

In [108]:
# Min value of entire array and its row and column

print("Min a = ", a.min())
c = np.unravel_index(np.argmin(a), a.shape)
print("Row and Column of {} is ([{}], [{}])".format(a.min(), c[0], c[1]))

Min a =  105
Row and Column of 105 is ([0], [0])


### Task 4

In [111]:
a = np.arange(1,21).reshape(4,5)

print("***Contents of array a\n", a)

***Contents of array a
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [114]:
# 4a
# Cumulative Sum along x-axis

print("***Cumulative SUM along x-axis\n", np.cumsum(a, axis=0))

***Cumulative SUM along x-axis
 [[ 1  2  3  4  5]
 [ 7  9 11 13 15]
 [18 21 24 27 30]
 [34 38 42 46 50]]


In [116]:
# Cumulative Sum along y-axis

print("***Cumulative SUM along y-axis\n", np.cumsum(a, axis=1))

***Cumulative SUM along y-axis
 [[ 1  3  6 10 15]
 [ 6 13 21 30 40]
 [11 23 36 50 65]
 [16 33 51 70 90]]


In [117]:
# 4b
# Cumulative Product along x-axis

print("***Cumulative PRODUCT along x-axis\n", np.cumprod(a, axis=0))

***Cumulative PRODUCT along x-axis
 [[    1     2     3     4     5]
 [    6    14    24    36    50]
 [   66   168   312   504   750]
 [ 1056  2856  5616  9576 15000]]


In [118]:
# Cumulative Product along y-axis

print("***Cumulative PRODUCT along y-axis\n", np.cumprod(a, axis=1))

***Cumulative PRODUCT along y-axis
 [[      1       2       6      24     120]
 [      6      42     336    3024   30240]
 [     11     132    1716   24024  360360]
 [     16     272    4896   93024 1860480]]


## Section 12: File I/O on Numpy Arrays

### Task 1

### dtype - https://numpy.org/doc/stable/reference/arrays.dtypes.html

In [207]:
# Read the csv file

fname = "Data/singapore-residents-by-ethnic-group-and-sex-end-june-annual.csv"
data = np.loadtxt(fname, skiprows=1, dtype=[("year","i8"),("level1","U50"),("value","i8")], delimiter=",")

In [208]:
# Count total rows of data in the file

print("There are altogether {} rows of data in the file {}".format(data.shape[0], fname))

There are altogether 855 rows of data in the file Data/singapore-residents-by-ethnic-group-and-sex-end-june-annual.csv


In [209]:
# Identify unique number of years

data_years = data["year"]
print("There are {} years of data captured from {} to {}".format(np.unique(data_years).shape[0], data_years.min(), data_years.max()))

There are 57 years of data captured from 1960 to 2016


In [210]:
# Identify highest total number of residents and year (Boolean Masking)

b = data["level1"] == "Total Residents" # Firstly, extract the correct Column then identify what values will fit the criteria
c = data[b]["value"].max() # Returns the highest value from Column "value"
d = data[b]["value"].argmax() # Returns the index value of the highest value from Column "value"

print("Year with the highest total number of residents: {}\nPopulation Count: {}".format(data[b]["year"][d], c))

Year with the highest total number of residents: 2016
Population Count: 3933559


In [211]:
# keyword = 'Total Residents' # Identify what is to search for within the Row
# column_to_search = data['level1'] # Identify what Column to focus the search on
# out = [i for i, v in enumerate(column_to_search) if keyword in v] # Extracts the Row position when "Total Residents" is listed
# data_totalresidents = data[out] # Extracts only the Rows with "Total Residents" to the data_totalresidents variable

In [212]:
# Identify lowest total number of residents and year

e = data["level1"] == "Total Residents" # Boolean mask for when value of the Column "level1" is "Total Residents"
f = data[e]["value"].min() # Returns the minimum value of the "value" Column, which is listing the lowest total number of residents
g = data[e]["value"].argmin() # Returns the index position of the min value of the "value" Column

print("Year with the lowes total number of residents: {}\nPopulation Count: {}".format(data[g]["year"], f))

Year with the lowes total number of residents: 1960
Population Count: 1646400


### The End
### Thank you!